-- AlterTable
ALTER TABLE `books` ADD COLUMN `deleted_at` DATETIME(3) NULL,
    ADD COLUMN `quantity` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
